# Generated by Django 3.1.4 on 2020-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0004_auto_20201210_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blogg/static/blogg/images/'),
        ),
    ]
