# Generated by Django 3.1.4 on 2020-12-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogg', '0006_auto_20201210_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_image',
        ),
    ]
